%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\cenmk\OneDrive - University of Leeds\Documents\CFD\Chamber Benchmark\Anemometry\1_poles5_slot.txt
%
% Auto-generated by MATLAB on 11-Mar-2020 10:56:16

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];
opts = setvaropts(opts, [2, 3], "TrimNonNumeric", true);
opts = setvaropts(opts, [2, 3], "ThousandsSeparator", ",");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
poles5slot = readtable("2_poles5_slot.txt", opts);

%% Convert to output type
poles5slot = table2array(poles5slot);

%% Clear temporary variables
clear opts

%%
line=poles5slot; %CFD_025
vel(:,1)=line(:,4);

PT=zeros(4,1);
E=zeros(4,1);

for k=1:4
    PT(k,1)=mean(vel((k-1)*1200+1:(k)*1200,1));
    E(k,1)=std(vel((k-1)*1200+1:(k)*1200,1));
end

% for i=1:4%:-1:1
%         sumtot=0;
%         av=0;
%         t=(i-1)*1200+1;
%         e=0;
%         sum=0;
%         n=1;
%     for j=t:1200*i
%         sumtot=sumtot+vel(j,1);
%         av=sumtot/1200.;
%     end 
%     
%      for j=t:1200*i
%         sum=sum+(vel(j,1)-av).^2.;
%         e=sqrt(1/(n-1)*sum);
%         %e=std(vel,0,240);
%         n=n+1;
%      end
%     PT(i,1)=av;
%     E(i,1)=e;
% end

x=1.65:-0.4:0.4;
h=herrorbar(PT,x,E,'+k');
hold on

pke=plot(KERNG(:,1),-KERNG(:,2),'ro');
prsm=plot(RSM(:,1),-RSM(:,2),'bs');
pkw=plot(KW(:,1),-KW(:,2),'gd');


fid=fopen('pole_2_TurbI_chamber_05_RSM.xy');
[x ~] = textscan (fid, '%f %f', 'HeaderLines', 4);
fclose(fid);
v(:,1)=cell2mat(x(:,1));
v(:,2)=cell2mat(x(:,2));
v=sortrows(v,2);
% fig
plot(v(:,1),-v(:,2),'ro');




poles=importdata('pole_2_cfd.dat');
pole(:,1)=poles(:,1);
s=size(pole);
dim=s(:,1);
space=2.26/dim;
if mod(2,dim)~=0
    fin=space;
else
    fin=0.0;
end
xx=2.26:-space:fin;
plot(pole,xx,'bo','markersize',5, 'linewidth',1.5)
ylabel({'Height (m)'});
xlabel({'Velocity magnitude (m/s)'});
hold off
%xx=2.26:-0.0491:0.0491;
%plot(pole,xx,'ro')